LinkHubUI/LinkHubUI/Areas/User/Controllers/URLController.cs
using BLL;
using BOL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinkHubUI.Areas.User.Controllers
{
    public class URLController : Controller
    {
        private UrlBs objBs;
        private CategoryBs objCatBs;
        private UserBs objUserBs;

        public URLController()
        {
            objBs = new UrlBs();
            objCatBs = new CategoryBs();
            objUserBs = new UserBs();
        }

        public ActionResult Index()
        {
            ViewBag.CategoryId = new SelectList(objCatBs.GetALL().ToList(), "CategoryId", "CategoryName");
            ViewBag.UserId = new SelectList(objUserBs.GetALL().ToList(), "UserId", "UserEmail");
            return View();
        }
        //
        // GET: /User/URL/


        [HttpPost]
        public ActionResult Create(tbl_Url myUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objBs.Insert(myUrl);
                    TempData["Msg"] = "Created Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.CategoryId = new SelectList(objCatBs.GetALL().ToList(), "CategoryId", "CategoryDesc");
                    ViewBag.UserId = new SelectList(objUserBs.GetALL().ToList(), "UserId", "UserEmail");
                    return View("Index");
                }
            }
            catch (Exception e1)
            {
                TempData["Msg"] = "Create Failed: " + e1.Message;
                return RedirectToAction("Index");
            }
        }

    }
}

LinkHubUI/LinkHubUI/Areas/User/Views/URL/Index.cshtml
@model BOL.tbl_Url

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@if(TempData["Msg"]!=null)
{
    <h3>
        @TempData["Msg"].ToString()
    </h3>
}

@using (Html.BeginForm("Create","URL", FormMethod.Post)) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h4>tbl_Url</h4>


        <div class="form-group">
            @Html.LabelFor(model => model.UrlTitle, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlTitle)
                @Html.ValidationMessageFor(model => model.UrlTitle)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlDesc, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlDesc)
                @Html.ValidationMessageFor(model => model.UrlDesc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.UserId, new { @class = "control-label col-md-2" })
        
        <div class="col-md-10">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
            @Html.EditorFor(model => model.IsApproved)
            @Html.ValidationMessageFor(model => model.IsApproved)
        </div>
            </div>
       
        <p>
            <input type="submit" value="Create" />
        </p>
 </div>
    
       
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")}